### ISSUE TITLE
Update package.json on Vendure release

### ISSUE THREAD

**Issue by drewterry** [vendure-ecommerce/plugin-template#2]
This repo still points to vendure 0.13.0, when 0.14.0 was released last week.  I know the main repo releases everything at once, but it would be nice to update the plugin-template as well.

**Comment by michaelbromley** [comment]
Fixed by you ;)

**Comment by drewterry** [comment]
Do you think this could be updated automatically when vendure releases new
updates?  I'm not sure how your ci pipeline is set up.

**Comment by michaelbromley** [comment]
Ah I didn't get that you meant to automate it. Hmm... In theory the version could be bumped by a CI action, but this could get tricky when there are breaking changes that mean manual changes are needed to some of the code in the template.

**Comment by drewterry** [comment]
Fair point
